routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\MegaTagController;

use App\Http\Controllers\Admin\AjaxController;
use App\Http\Controllers\Admin\SupplyChainController;
use App\Http\Controllers\Admin\DirectorController;
use App\Http\Controllers\Admin\AccountantController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\BankController;
use App\Http\Controllers\Admin\BankAccountController;
use App\Http\Controllers\Admin\AccountCategoryController;
use App\Http\Controllers\Admin\CurAccountCategoryController;
use App\Http\Controllers\Admin\SubAccountCategoryController;
use App\Http\Controllers\Admin\VoucharController;
use App\Http\Controllers\Admin\DepartmentBankController;
use App\Http\Controllers\Admin\ChequeBankController;



use App\Http\Controllers\Admin\ModuleController;
use App\Http\Controllers\ForgetPasswordResetController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('contactUs', [ContactUsController::class,'index'])->name('contactUs.index');
// Route::post('contactUs/store', [ContactUsController::class,'AjaxCallForContactUs'])->name('AjaxCallForContactUs');

Route::get('migration', function () {
    return Artisan::call('migrate');
});

Route::get('seed', function () {
    return Artisan::call('db:seed');
});


Route::get('/forgotpassword/{type}',            [ForgetPasswordResetController::class, 'viewForgotpassword'])                 ->name('forgotpassword');
Route::get('/resetPassword/{email_encode}',     [ForgetPasswordResetController::class, 'ResetPassword'])                      ->name('resetPassword'); // Forgot Password send email 
Route::post('/SetNewPassword',                  [ForgetPasswordResetController::class, 'SetNewPassword'])                     ->name('SetNewPassword'); // Set New Password 
Route::post('/AjaxCallForForgotPasswordEmail',  [ForgetPasswordResetController::class, 'AjaxCallForForgotPasswordEmail'])     ->name('AjaxCallForForgotPasswordEmail'); // Forgot Password send email 

// Route::get('/test', function () {
//     return "test";
// });

Route::get('/', [AuthController::class, 'loginShow']);

Route::prefix('admin')->group(function () {
    Route::get('/login',            [AuthController::class, 'loginShow'])       ->name('admin.login')           ->middleware('guest:admin');
    Route::get('/logout',           [AuthController::class, 'logout'])          ->name('admin.logout')          ->middleware('auth:admin');
    Route::post('/login',           [AuthController::class, 'loginPost'])       ->name('admin.login.store');
    Route::post('/passwordchange',  [AuthController::class, 'changePassword'])  ->name('admin.changePassword')  ->middleware('auth:admin');

    Route::middleware('auth:admin')->group(function () {
        // Custom Route
        Route::get('/',                     [HomeController::class,'index'])                ->name('admin.home');
        Route::get('user/permissions/{id}', [PermissionsController::class,'permissions'])   ->name('auth.user.permissions');
        Route::post('user/permissions',     [PermissionsController::class,'setPermissions'])->name('auth.user.permissions.post');  

        Route::post('supplyChain/bulkUpdate',[SupplyChainController::class,'bulkUpdate'])->name('supplyChain.bulkUpdate');
        Route::get('supplyChain/bulkEdit/{json_request}',[SupplyChainController::class,'bulkEdit'])->name('supplyChain.bulkEdit');
        Route::get('supplyChain/bulkPDF/{json_request}',[SupplyChainController::class,'bulkPDF'])->name('supplyChain.bulkPDF');
        Route::get('supplyChain/approve/{json_request}',[SupplyChainController::class,'bulkApprove'])->name('supplyChain.bulkApprove');
        Route::post('supplyChain/storeApproved',[SupplyChainController::class,'storeApproved'])->name('supplyChain.storeApproved');
        Route::get('supplyChain/supplyChainNotInProcessPagination',[SupplyChainController::class,'ajaxCallForSupplyChainNotInProcessPagination'])->name('supplyChain.notInProcess');
        Route::get('supplyChain/supplyChainCompletePagination',[SupplyChainController::class,'ajaxCallForSupplyChainCompletePagination'])->name('supplyChain.complete');


        Route::post('accountant/bulkUpdate',[AccountantController::class,'bulkUpdate'])->name('accountant.bulkUpdate');
        Route::get('accountant/approve/{json_request}',[AccountantController::class,'bulkApproveByAccountant'])->name('accountant.bulkApproveByAccountant');
        Route::post('accountant/storeApproved',[AccountantController::class,'storeApprovedByAccountant'])->name('accountant.storeApprovedByAccountant');

        // Ajax calls
        Route::post('vendorByDepartment', [AjaxController::class,'getVendorByDepartment'])->name('getVendorByDepartment');
        Route::post('vendorByName', [AjaxController::class,'getVendorByName'])->name('getVendorByName');
        Route::post('MainCategoryByDepartment', [CurAccountCategoryController::class,'getMainCategoryByDepartment'])->name('getMainCategoryByDepartment');
        Route::post('CurCategoryByDepartment', [SubAccountCategoryController::class,'getCurCategoryByDepartment'])->name('getCurCategoryByDepartment');
        Route::post('subCategoryByDepartment', [AjaxController::class,'getSubCategoryByDepartment'])->name('getSubCategoryByDepartment');
        Route::post('vendorDetail', [AjaxController::class,'getVendorDetail'])->name('getVendorDetail');
        Route::post('VendorBySubCategory', [AjaxController::class,'getVendorBySubCategory'])->name('getVendorBySubCategory');
        Route::post('getItemDetailFromLocal', [AjaxController::class,'getItemDetailFromLocal'])->name('getItemDetailFromLocal');

        Route::get('accountCategory/import', [AccountCategoryController::class,'importView'])->name('mainCategory.importView');
        Route::post('accountCategory/import', [AccountCategoryController::class,'import'])->name('mainCategory.import');

        Route::get('curAccountCategory/import', [CurAccountCategoryController::class,'importView'])->name('curCategory.importView');
        Route::post('curAccountCategory/import', [CurAccountCategoryController::class,'import'])->name('curCategory.import');

        Route::get('subAccountCategory/import', [SubAccountCategoryController::class,'importView'])->name('subCategory.importView');
        Route::post('subAccountCategory/import', [SubAccountCategoryController::class,'import'])->name('subCategory.import');
        
        Route::get('vendor/import', [VendorController::class,'importView'])->name('vendor.importView');
        Route::post('vendor/import', [VendorController::class,'import'])->name('vendor.import');
        Route::get('vendor/vendorPagination',[VendorController::class,'ajaxCallForVendorPagination'])->name('vendor.pagination');

        Route::get('accountant/vouchar/chequePrint', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        Route::get('accountant/vouchar/voucharPDF/{json}', [VoucharController::class,'voucharPDF'])->name('vouchar.voucharPDF');
        Route::get('accountant/vouchar/viewExport', [VoucharController::class,'viewExport'])->name('vouchar.viewExport');
        Route::post('accountant/voucharDetailExport', [VoucharController::class,'voucharDetailExport'])->name('vouchar.voucharDetailExport');
        Route::get('accountant/vouchar/{id}', [VoucharController::class,'createVouchar'])->name('vouchar.createVouchar');
        Route::get('accountant/vouchar/cheques/{id}', [VoucharController::class,'chequeBlade'])->name('vouchar.chequeBlade');
        // Route::get('accountant/vouchar/cheque/{id}', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        // Route::post('accountant/vouchar/cheque', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        
        Route::resource('users',   UsersController::class);
        Route::resource('supplyChain', SupplyChainController::class);
        Route::resource('director', DirectorController::class);
        Route::resource('accountant', AccountantController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('paymentType', PaymentTypeController::class);
        Route::resource('department', DepartmentController::class);
        Route::resource('vendor', VendorController::class);
        Route::resource('bank', BankController::class);
        Route::resource('bankAccount', BankAccountController::class);
        Route::resource('accountCategory', AccountCategoryController::class);
        Route::resource('curAccountCategory', CurAccountCategoryController::class);
        Route::resource('subAccountCategory', SubAccountCategoryController::class);

        Route::resource('accountant/vouchar', VoucharController::class);

        Route::resource('module', ModuleController::class);

        Route::resource('departmentBank', DepartmentBankController::class);
        Route::resource('cheque', ChequeBankController::class);
    });
});

resources/views/admin/module/create.blade.php
@extends('admin.layouts.app')

@push('custom-css')

  <style>
    .center{
      text-align: center !important;
    }
    .border-top-bottom{
      border-top: 1px solid #adacac;
      border-bottom: 1px solid #adacac;
      background-color: #adacac;
    }
  </style>
@endpush

@section('content')
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card card-primary mt-4">
            <div class="card-header">
              <h3 class="card-title">Add Module</h3>
            </div>
            @include('errors.messages')

            <form id="quickForm" action="{{route('module.store')}}" method="post" enctype="multipart/form-data">
              @csrf
              @if (isset($data->id))
                <input type="hidden" name="id" value="{{ @$data->id }}">
              @endif
              <div class="card-body row">
                <div class="form-group col-md-12">
                    <label for="name">Module Name</label>
                    <input type="text" name="name" class="form-control" value="{{old('name',@$data->name)}}" id="">
                    @error('name')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror
                </div>

                <div class="form-group col-md-12">
                  <h3 class="border-top-bottom center">Repository</h3>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="repository_check" id="repository_check" > Module Repository
                    @error('repository_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>

                <div class="form-group col-md-12">
                  <h3 class="border-top-bottom center">Model</h3>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="model_migration_check" id="model_migration_check" > Model With Migration
                    @error('model_migration_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="model_check" id="model_check" > Model
                    @error('model_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>
                
                <div class="form-group col-md-12">
                  <h3 class="border-top-bottom center">Controller</h3>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="resource_controller_check" id="resource_controller_check" > Resource Controller
                    @error('resource_controller_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="controller_check" id="controller_check" > Controller
                    @error('controller_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>
                
                <div class="form-group col-md-12">
                  <h3 class="border-top-bottom center">View files</h3>
                </div>

                <div class="form-group col-md-3">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="index_blade_check" id="index_blade_check" > Index Blade
                    @error('index_blade_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>

                <div class="form-group col-md-3">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="create_blade_check" id="create_blade_check" > Create Blade
                    @error('create_blade_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>

                <div class="form-group col-md-3">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="edit_blade_check" id="edit_blade_check" > Edit Blade
                    @error('edit_blade_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>

                <div class="form-group col-md-3">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="show_blade_check" id="show_blade_check" > Show Blade
                    @error('show_blade_check')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div>

                {{-- <div class="form-group col-md-12">
                    <div class="form-check ">
                    <input type="checkbox" class="form-check-input" name="status" id="status" checked>  Is Active?
                    @error('status')
                    <p class="text-danger text-sm">{{$message}}</p>
                    @enderror 
                    </div>
                </div> --}}
               
              </div>
              <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="submit_btn"> {{!isset($data)? 'Create':'Update'}}</button>
                {{-- <a href="{{route('module.index')}}" class="btn btn-default">Back</a> --}}
                <a href="{{route('admin.home')}}" class="btn btn-default">Back</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

@push('custom-script')


<script>
 
  $('#model_migration_check').click(function () { 
    document.getElementById("model_check").checked = false;
  });
  
  $('#model_check').click(function () { 
    document.getElementById("model_migration_check").checked = false;
  });
  
  $('#resource_controller_check').click(function () { 
    document.getElementById("controller_check").checked = false;
  });
  
  $('#controller_check').click(function () { 
    document.getElementById("resource_controller_check").checked = false;
  });

  $('#submit_btn').click(function (e) {
    e.preventDefault();

    Swal.fire({
      title: 'Do you want to save the changes?',
      showCancelButton: true,
      confirmButtonText: `Save`,
    }).then((result) => {
      /* Read more about isConfirmed, isDenied below */
      if (result.isConfirmed) {
        // Swal.fire('Saved!', '', 'success')
        $('#quickForm').submit();
      } else {
        Swal.fire('Changes are not saved', '', 'info')
      }
    })
  })

</script>
@endpush