routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\MegaTagController;

use App\Http\Controllers\Admin\AjaxController;
use App\Http\Controllers\Admin\SupplyChainController;
use App\Http\Controllers\Admin\DirectorController;
use App\Http\Controllers\Admin\AccountantController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\BankController;
use App\Http\Controllers\Admin\BankAccountController;
use App\Http\Controllers\Admin\AccountCategoryController;
use App\Http\Controllers\Admin\CurAccountCategoryController;
use App\Http\Controllers\Admin\SubAccountCategoryController;
use App\Http\Controllers\Admin\VoucharController;
use App\Http\Controllers\Admin\DepartmentBankController;
use App\Http\Controllers\Admin\ChequeBankController;



use App\Http\Controllers\Admin\ModuleController;
use App\Http\Controllers\ForgetPasswordResetController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('contactUs', [ContactUsController::class,'index'])->name('contactUs.index');
// Route::post('contactUs/store', [ContactUsController::class,'AjaxCallForContactUs'])->name('AjaxCallForContactUs');

Route::get('migration', function () {
    return Artisan::call('migrate');
});

Route::get('seed', function () {
    return Artisan::call('db:seed');
});


Route::get('/forgotpassword/{type}',            [ForgetPasswordResetController::class, 'viewForgotpassword'])                 ->name('forgotpassword');
Route::get('/resetPassword/{email_encode}',     [ForgetPasswordResetController::class, 'ResetPassword'])                      ->name('resetPassword'); // Forgot Password send email 
Route::post('/SetNewPassword',                  [ForgetPasswordResetController::class, 'SetNewPassword'])                     ->name('SetNewPassword'); // Set New Password 
Route::post('/AjaxCallForForgotPasswordEmail',  [ForgetPasswordResetController::class, 'AjaxCallForForgotPasswordEmail'])     ->name('AjaxCallForForgotPasswordEmail'); // Forgot Password send email 

// Route::get('/test', function () {
//     return "test";
// });

Route::get('/', [AuthController::class, 'loginShow']);

Route::prefix('admin')->group(function () {
    Route::get('/login',            [AuthController::class, 'loginShow'])       ->name('admin.login')           ->middleware('guest:admin');
    Route::get('/logout',           [AuthController::class, 'logout'])          ->name('admin.logout')          ->middleware('auth:admin');
    Route::post('/login',           [AuthController::class, 'loginPost'])       ->name('admin.login.store');
    Route::post('/passwordchange',  [AuthController::class, 'changePassword'])  ->name('admin.changePassword')  ->middleware('auth:admin');

    Route::middleware('auth:admin')->group(function () {
        // Custom Route
        Route::get('/',                     [HomeController::class,'index'])                ->name('admin.home');
        Route::get('user/permissions/{id}', [PermissionsController::class,'permissions'])   ->name('auth.user.permissions');
        Route::post('user/permissions',     [PermissionsController::class,'setPermissions'])->name('auth.user.permissions.post');  

        Route::post('supplyChain/bulkUpdate',[SupplyChainController::class,'bulkUpdate'])->name('supplyChain.bulkUpdate');
        Route::get('supplyChain/bulkEdit/{json_request}',[SupplyChainController::class,'bulkEdit'])->name('supplyChain.bulkEdit');
        Route::get('supplyChain/bulkPDF/{json_request}',[SupplyChainController::class,'bulkPDF'])->name('supplyChain.bulkPDF');
        Route::get('supplyChain/approve/{json_request}',[SupplyChainController::class,'bulkApprove'])->name('supplyChain.bulkApprove');
        Route::post('supplyChain/storeApproved',[SupplyChainController::class,'storeApproved'])->name('supplyChain.storeApproved');
        Route::get('supplyChain/supplyChainNotInProcessPagination',[SupplyChainController::class,'ajaxCallForSupplyChainNotInProcessPagination'])->name('supplyChain.notInProcess');
        Route::get('supplyChain/supplyChainCompletePagination',[SupplyChainController::class,'ajaxCallForSupplyChainCompletePagination'])->name('supplyChain.complete');


        Route::post('accountant/bulkUpdate',[AccountantController::class,'bulkUpdate'])->name('accountant.bulkUpdate');
        Route::get('accountant/approve/{json_request}',[AccountantController::class,'bulkApproveByAccountant'])->name('accountant.bulkApproveByAccountant');
        Route::post('accountant/storeApproved',[AccountantController::class,'storeApprovedByAccountant'])->name('accountant.storeApprovedByAccountant');

        // Ajax calls
        Route::post('vendorByDepartment', [AjaxController::class,'getVendorByDepartment'])->name('getVendorByDepartment');
        Route::post('vendorByName', [AjaxController::class,'getVendorByName'])->name('getVendorByName');
        Route::post('MainCategoryByDepartment', [CurAccountCategoryController::class,'getMainCategoryByDepartment'])->name('getMainCategoryByDepartment');
        Route::post('CurCategoryByDepartment', [SubAccountCategoryController::class,'getCurCategoryByDepartment'])->name('getCurCategoryByDepartment');
        Route::post('subCategoryByDepartment', [AjaxController::class,'getSubCategoryByDepartment'])->name('getSubCategoryByDepartment');
        Route::post('vendorDetail', [AjaxController::class,'getVendorDetail'])->name('getVendorDetail');
        Route::post('VendorBySubCategory', [AjaxController::class,'getVendorBySubCategory'])->name('getVendorBySubCategory');
        Route::post('getItemDetailFromLocal', [AjaxController::class,'getItemDetailFromLocal'])->name('getItemDetailFromLocal');

        Route::get('accountCategory/import', [AccountCategoryController::class,'importView'])->name('mainCategory.importView');
        Route::post('accountCategory/import', [AccountCategoryController::class,'import'])->name('mainCategory.import');

        Route::get('curAccountCategory/import', [CurAccountCategoryController::class,'importView'])->name('curCategory.importView');
        Route::post('curAccountCategory/import', [CurAccountCategoryController::class,'import'])->name('curCategory.import');

        Route::get('subAccountCategory/import', [SubAccountCategoryController::class,'importView'])->name('subCategory.importView');
        Route::post('subAccountCategory/import', [SubAccountCategoryController::class,'import'])->name('subCategory.import');
        
        Route::get('vendor/import', [VendorController::class,'importView'])->name('vendor.importView');
        Route::post('vendor/import', [VendorController::class,'import'])->name('vendor.import');
        Route::get('vendor/vendorPagination',[VendorController::class,'ajaxCallForVendorPagination'])->name('vendor.pagination');

        Route::get('accountant/vouchar/chequePrint', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        Route::get('accountant/vouchar/voucharPDF/{json}', [VoucharController::class,'voucharPDF'])->name('vouchar.voucharPDF');
        Route::get('accountant/vouchar/viewExport', [VoucharController::class,'viewExport'])->name('vouchar.viewExport');
        Route::post('accountant/voucharDetailExport', [VoucharController::class,'voucharDetailExport'])->name('vouchar.voucharDetailExport');
        Route::get('accountant/vouchar/{id}', [VoucharController::class,'createVouchar'])->name('vouchar.createVouchar');
        Route::get('accountant/vouchar/cheques/{id}', [VoucharController::class,'chequeBlade'])->name('vouchar.chequeBlade');
        // Route::get('accountant/vouchar/cheque/{id}', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        // Route::post('accountant/vouchar/cheque', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        
        Route::resource('users',   UsersController::class);
        Route::resource('supplyChain', SupplyChainController::class);
        Route::resource('director', DirectorController::class);
        Route::resource('accountant', AccountantController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('paymentType', PaymentTypeController::class);
        Route::resource('department', DepartmentController::class);
        Route::resource('vendor', VendorController::class);
        Route::resource('bank', BankController::class);
        Route::resource('bankAccount', BankAccountController::class);
        Route::resource('accountCategory', AccountCategoryController::class);
        Route::resource('curAccountCategory', CurAccountCategoryController::class);
        Route::resource('subAccountCategory', SubAccountCategoryController::class);

        Route::resource('accountant/vouchar', VoucharController::class);

        Route::resource('module', ModuleController::class);

        Route::resource('departmentBank', DepartmentBankController::class);
        Route::resource('cheque', ChequeBankController::class);
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'created_by',
        'updated_by',
        'deleted_by',
    ];
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repository\CategoryRepositoryInterface;
use Auth;
use DB;
use Validator;
use Session;
use Redirect;

class CategoryController extends Controller
{
    private $categoryRepository;

    private $permissionView;
    private $permissionCreate;
    private $permissionEdit;
    private $permissionDelete;
    
    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;

        // for permissions
        $this->permissionView       = 'category-view';
        $this->permissionCreate     = 'category-create';
        $this->permissionEdit       = 'category-edit';
        $this->permissionDelete     = 'category-delete';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->hasPermissionTo($this->permissionView))
        {
            $data = $this->categoryRepository->allDesc();
            return view('admin.categories.index',\compact('data'));
        }
        else
        {
            return view('errors.401');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->hasPermissionTo($this->permissionCreate))
        {
            return view('admin.categories.create');
        }
        else
        {
            return view('errors.401');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' =>  'required',
        ]);

        if($validator->fails())
        {
            return Redirect::back()->withInput($request->input())->withErrors($validator);
        }

        try {
            
            $user_id = Auth::user()->id;
            if(isset($request->id))
            {
                $attributes = [
                    'name'          => $request->name,
                    'updated_by'    => $user_id,
                ];
                $object = $this->categoryRepository->update($attributes,$request->id);
            }
            else{
                $attributes = [
                    'name'          => $request->name,
                    'created_by'    => $user_id,
                ];
                $this->categoryRepository->create($attributes);
            }
            
        } 
        catch (\Throwable $th) 
        {
            return redirect()->back()->with('error','Some thing is wrong!');
        }
        return redirect()->route('category.index')->with('success','Data is Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->hasPermissionTo($this->permissionEdit))
        {
            $data = $this->categoryRepository->find($id);
            return view('admin.categories.create',compact('data'));
        }
        else
        {
            return view('errors.401');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->hasPermissionTo($this->permissionDelete))
        {
            // dd('delete');
            try {
                $object = $this->categoryRepository->find($id);
                if($object)
                {
                    $this->categoryRepository->delete($id);
                }
            } 
            catch (\Throwable $th) {
                return response()->json([
                    'status' => false,
                    'msg' => 'Record is not deleted!',
                ]);
            }
            return response()->json([
                'status' => true,
                'msg' => 'Data is Successfully Deleted!',
            ]);
        }
        else
        {
            return view('errors.401');
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@push('custom-css')

<style>
    /* .text-limit {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        max-width: 150px;
    }

    .center {
        display: flex;
        justify-content: center;
        align-items: center;
    } */

</style>
@endpush

@section('content')

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card mt-4">
                        <div class="card-header">
                            <h3 class="card-title">Add Category</h3>
                        </div>
                        @include('errors.messages')
                        <div class="card-body">
                            <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                @if (isset($data->id))
                                    <input type="hidden" name="id" value="{{ @$data->id }}">
                                @endif
                                <div class="card-body row">
                                    <div class="form-group col-md-12">
                                        <label>Name</label>
                                        <input type="text" name="name" class="form-control" value="{{(old('name')!=null)? (old('name')):(@$data->name)}}" >
                                        @error('name')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror  
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-info">Submit</button>
                                <a href="{{route('category.index')}}" class="btn btn-default">Back</a>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>

      

       

        
    </section>

</div>

@endsection


@push('custom-script')

<script>
    $(function () {
        $("#data-table").DataTable();
    });

    $("#add_detail").click(function(){  
        $('tbody').append($("#data_row").html());
        // $('.export-cargo-detail-date').val($('#of_date').val());
    });

    $("table").on("click", ".deleteRow", function() {
        $(this).closest("tr").remove();
    });

    $('.chq_name_select').click(function (e) { 
        e.preventDefault();
        // console.log($(this).html());
        $('.chq_name_input').val($(this).html());
    });
   

</script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@push('custom-css')

<style>
    .text-limit {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        max-width: 150px;
    }

    .center {
        display: flex;
        justify-content: center;
        align-items: center;
    }

</style>
@endpush

@section('content')

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card  mt-4">
                        <div class="card-header">
                            <h3 class="card-title">View Categories</h3>
                            @can('category-create')
                            <a class="btn btn-success btn-sm float-right" href="{{route('category.create')}}">
                                Add Record
                            </a>    
                            @endcan
                        </div>
                        <form action="" method="GET" id="supply_chain_form">
                            {{-- @csrf --}}
                            <div class="card-body">
                                @include('errors.messages')
                                <table class="table table-bordered table-striped" id="data-table">
                                    <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Name</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php
                                            $i = 1;
                                        @endphp
                                        @foreach ($data as $key => $item)
                                        <tr>
                                            
                                            
                                            <td>{{$i++}}</td> 
                                            <td>{{@$item->name}}</td> 
                                            <td class="center">

                                                @can('category-edit')
                                                    <a class="btn btn-primary btn-sm ml-1" href="{{route('category.edit',$item->id)}}" data-toggle="tooltip" data-placement="top" title="edit">
                                                        <i class="fas fa-edit"></i>
                                                    </a>      
                                                @endcan
                                               
                                                @can('category-delete')
                                                    <button class="btn btn-danger btn-sm ml-1 btn-delete" data-id="{{$item->id}}" data-toggle="tooltip" data-placement="top" title="Delete">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                @endcan
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                           
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>

</div>



@endsection


@push('custom-script')


<script>
    $(function () {
        $("#data-table").DataTable();
    });

    $('.btn-delete').click(function (e) {
        e.preventDefault();
        let _this = $(this);
        let id = _this.data('id'); 
        // let form = _this.closest('form');
        Swal.fire({
            title: 'Are you sure, you want to Delete the selected record?',
            showDenyButton: true,
            // showCancelButton: true,
            confirmButtonText: `Yes`,
            denyButtonText: `No`,
        }).then((result) => {
            /* Read more about isConfirmed, isDenied below */
            if (result.isConfirmed) {
                $.ajax({
                    url: "category/"+id,
                    type: "DELETE",
                    data: {
                        "id": id,
                        "_token": '{{ csrf_token() }}',
                    },
                    success: function (response) {
                        console.log('response',response['status']);
                        if(response['status'])
                        {
                            $('#success_msg_id').text(response['msg']);
                            $('#success_msg').show();
                            _this.closest('tr').remove();
                        }
                        else{
                            $('#error_msg_id').text(response['msg']);
                            $('#error_msg').show();
                        }
                        $(".alert-dismissible").fadeOut(5000);

                    }
                });
            } 
            else if (result.isDenied) {
                Swal.fire('Changes are not saved', '', 'info')
            }
        })
    })

</script>
@endpush