routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\MegaTagController;

use App\Http\Controllers\Admin\AjaxController;
use App\Http\Controllers\Admin\SupplyChainController;
use App\Http\Controllers\Admin\DirectorController;
use App\Http\Controllers\Admin\AccountantController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\PaymentTypeController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\VendorController;
use App\Http\Controllers\Admin\BankController;
use App\Http\Controllers\Admin\BankAccountController;
use App\Http\Controllers\Admin\AccountCategoryController;
use App\Http\Controllers\Admin\CurAccountCategoryController;
use App\Http\Controllers\Admin\SubAccountCategoryController;
use App\Http\Controllers\Admin\VoucharController;
use App\Http\Controllers\Admin\DepartmentBankController;
use App\Http\Controllers\Admin\ChequeBankController;



use App\Http\Controllers\Admin\ModuleController;
use App\Http\Controllers\ForgetPasswordResetController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('contactUs', [ContactUsController::class,'index'])->name('contactUs.index');
// Route::post('contactUs/store', [ContactUsController::class,'AjaxCallForContactUs'])->name('AjaxCallForContactUs');

Route::get('migration', function () {
    return Artisan::call('migrate');
});

Route::get('seed', function () {
    return Artisan::call('db:seed');
});


Route::get('/forgotpassword/{type}',            [ForgetPasswordResetController::class, 'viewForgotpassword'])                 ->name('forgotpassword');
Route::get('/resetPassword/{email_encode}',     [ForgetPasswordResetController::class, 'ResetPassword'])                      ->name('resetPassword'); // Forgot Password send email 
Route::post('/SetNewPassword',                  [ForgetPasswordResetController::class, 'SetNewPassword'])                     ->name('SetNewPassword'); // Set New Password 
Route::post('/AjaxCallForForgotPasswordEmail',  [ForgetPasswordResetController::class, 'AjaxCallForForgotPasswordEmail'])     ->name('AjaxCallForForgotPasswordEmail'); // Forgot Password send email 

// Route::get('/test', function () {
//     return "test";
// });

Route::get('/', [AuthController::class, 'loginShow']);

Route::prefix('admin')->group(function () {
    Route::get('/login',            [AuthController::class, 'loginShow'])       ->name('admin.login')           ->middleware('guest:admin');
    Route::get('/logout',           [AuthController::class, 'logout'])          ->name('admin.logout')          ->middleware('auth:admin');
    Route::post('/login',           [AuthController::class, 'loginPost'])       ->name('admin.login.store');
    Route::post('/passwordchange',  [AuthController::class, 'changePassword'])  ->name('admin.changePassword')  ->middleware('auth:admin');

    Route::middleware('auth:admin')->group(function () {
        // Custom Route
        Route::get('/',                     [HomeController::class,'index'])                ->name('admin.home');
        Route::get('user/permissions/{id}', [PermissionsController::class,'permissions'])   ->name('auth.user.permissions');
        Route::post('user/permissions',     [PermissionsController::class,'setPermissions'])->name('auth.user.permissions.post');  

        Route::post('supplyChain/bulkUpdate',[SupplyChainController::class,'bulkUpdate'])->name('supplyChain.bulkUpdate');
        Route::get('supplyChain/bulkEdit/{json_request}',[SupplyChainController::class,'bulkEdit'])->name('supplyChain.bulkEdit');
        Route::get('supplyChain/bulkPDF/{json_request}',[SupplyChainController::class,'bulkPDF'])->name('supplyChain.bulkPDF');
        Route::get('supplyChain/approve/{json_request}',[SupplyChainController::class,'bulkApprove'])->name('supplyChain.bulkApprove');
        Route::post('supplyChain/storeApproved',[SupplyChainController::class,'storeApproved'])->name('supplyChain.storeApproved');
        Route::get('supplyChain/supplyChainNotInProcessPagination',[SupplyChainController::class,'ajaxCallForSupplyChainNotInProcessPagination'])->name('supplyChain.notInProcess');
        Route::get('supplyChain/supplyChainCompletePagination',[SupplyChainController::class,'ajaxCallForSupplyChainCompletePagination'])->name('supplyChain.complete');


        Route::post('accountant/bulkUpdate',[AccountantController::class,'bulkUpdate'])->name('accountant.bulkUpdate');
        Route::get('accountant/approve/{json_request}',[AccountantController::class,'bulkApproveByAccountant'])->name('accountant.bulkApproveByAccountant');
        Route::post('accountant/storeApproved',[AccountantController::class,'storeApprovedByAccountant'])->name('accountant.storeApprovedByAccountant');

        // Ajax calls
        Route::post('vendorByDepartment', [AjaxController::class,'getVendorByDepartment'])->name('getVendorByDepartment');
        Route::post('vendorByName', [AjaxController::class,'getVendorByName'])->name('getVendorByName');
        Route::post('MainCategoryByDepartment', [CurAccountCategoryController::class,'getMainCategoryByDepartment'])->name('getMainCategoryByDepartment');
        Route::post('CurCategoryByDepartment', [SubAccountCategoryController::class,'getCurCategoryByDepartment'])->name('getCurCategoryByDepartment');
        Route::post('subCategoryByDepartment', [AjaxController::class,'getSubCategoryByDepartment'])->name('getSubCategoryByDepartment');
        Route::post('vendorDetail', [AjaxController::class,'getVendorDetail'])->name('getVendorDetail');
        Route::post('VendorBySubCategory', [AjaxController::class,'getVendorBySubCategory'])->name('getVendorBySubCategory');
        Route::post('getItemDetailFromLocal', [AjaxController::class,'getItemDetailFromLocal'])->name('getItemDetailFromLocal');

        Route::get('accountCategory/import', [AccountCategoryController::class,'importView'])->name('mainCategory.importView');
        Route::post('accountCategory/import', [AccountCategoryController::class,'import'])->name('mainCategory.import');

        Route::get('curAccountCategory/import', [CurAccountCategoryController::class,'importView'])->name('curCategory.importView');
        Route::post('curAccountCategory/import', [CurAccountCategoryController::class,'import'])->name('curCategory.import');

        Route::get('subAccountCategory/import', [SubAccountCategoryController::class,'importView'])->name('subCategory.importView');
        Route::post('subAccountCategory/import', [SubAccountCategoryController::class,'import'])->name('subCategory.import');
        
        Route::get('vendor/import', [VendorController::class,'importView'])->name('vendor.importView');
        Route::post('vendor/import', [VendorController::class,'import'])->name('vendor.import');
        Route::get('vendor/vendorPagination',[VendorController::class,'ajaxCallForVendorPagination'])->name('vendor.pagination');

        Route::get('accountant/vouchar/chequePrint', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        Route::get('accountant/vouchar/voucharPDF/{json}', [VoucharController::class,'voucharPDF'])->name('vouchar.voucharPDF');
        Route::get('accountant/vouchar/viewExport', [VoucharController::class,'viewExport'])->name('vouchar.viewExport');
        Route::post('accountant/voucharDetailExport', [VoucharController::class,'voucharDetailExport'])->name('vouchar.voucharDetailExport');
        Route::get('accountant/vouchar/{id}', [VoucharController::class,'createVouchar'])->name('vouchar.createVouchar');
        Route::get('accountant/vouchar/cheques/{id}', [VoucharController::class,'chequeBlade'])->name('vouchar.chequeBlade');
        // Route::get('accountant/vouchar/cheque/{id}', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        // Route::post('accountant/vouchar/cheque', [VoucharController::class,'viewChequeDetail'])->name('vouchar.chequePrint');
        
        Route::resource('users',   UsersController::class);
        Route::resource('supplyChain', SupplyChainController::class);
        Route::resource('director', DirectorController::class);
        Route::resource('accountant', AccountantController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('paymentType', PaymentTypeController::class);
        Route::resource('department', DepartmentController::class);
        Route::resource('vendor', VendorController::class);
        Route::resource('bank', BankController::class);
        Route::resource('bankAccount', BankAccountController::class);
        Route::resource('accountCategory', AccountCategoryController::class);
        Route::resource('curAccountCategory', CurAccountCategoryController::class);
        Route::resource('subAccountCategory', SubAccountCategoryController::class);

        Route::resource('accountant/vouchar', VoucharController::class);

        Route::resource('module', ModuleController::class);

        Route::resource('departmentBank', DepartmentBankController::class);
        Route::resource('cheque', ChequeBankController::class);
    });
});

resources/views/admin/partials/_modal.blade.php
<!-- Modal -->
<div class="modal fade" id="frontPagesModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        
      </div>
    </div>
  </div>

resources/views/admin/partials/aside.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link text-center">
    {{-- <img src="{{asset('public/backend/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo"
      class="brand-image img-circle elevation-3" style="opacity: .8"> --}}
    <span class="brand-text font-weight-light">Dream World</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{asset('public/backend/images/user-avatar.png')}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{@Auth::user()->name}}</a>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    {{-- <div class="form-inline">
<div class="input-group" data-widget="sidebar-search">
<input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
<div class="input-group-append">
<button class="btn btn-sidebar">
<i class="fas fa-search fa-fw"></i>
</button>
</div>
</div>
</div> --}}

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        {{-- @can('language-view')
        <li class="nav-item">
          <a href="{{route('language.index')}}"
            class="nav-link {{ ( Route::currentRouteName() == 'language.index' || Route::currentRouteName() == 'language.create' || Route::currentRouteName() == 'language.edit')? 'active' : '' }}">
            <i class="fas fa-language nav-icon"></i>
            <p>
              Language
            </p>
          </a>
        </li>
        @endcan --}}

        {{-- @can('menu-view')
        <li class="nav-item">
          <a href="{{route('menu.index')}}"
            class="nav-link {{ ( Route::currentRouteName() == 'menu.index' || Route::currentRouteName() == 'menu.create' || Route::currentRouteName() == 'menu.edit')? 'active' : '' }}">
            <i class="fas fa-bars nav-icon"></i>
            <p>
              Menu
            </p>
          </a>
        </li>
        @endcan --}}

        {{-- @can('faq-view')
        <li class="nav-item">
          <a href="{{route('faq.index')}}"
            class="nav-link {{ ( Route::currentRouteName() == 'faq.index' || Route::currentRouteName() == 'faq.create' || Route::currentRouteName() == 'faq.edit')? 'active' : '' }}">
            <i class="fas fa-comments nav-icon"></i>
            <p>
              FAQs
            </p>
          </a>
        </li>
        @endcan --}}

        

        @can('supply-chain-view')
        <li class="nav-item">
          <a href="{{route('supplyChain.index')}}"
            class="nav-link {{Request::segment(2)=='supplyChain'?'active':''}}">
            <i class="fas fa-clipboard-list nav-icon"></i>
            <p>
              Supply Chain
            </p>
          </a>
        </li>
        @endcan

        

        @can('accountant-view')
        <li class="nav-item">
          <a href="{{route('accountant.index')}}"
            class="nav-link {{Request::segment(2)=='accountant'?'active':''}}">
            <i class="fas fa-file-invoice-dollar nav-icon"></i>
            <p>
              Accountant
            </p>
          </a>
        </li>
        @endcan

        
        
        {{-- @can('bank-view')
        <li class="nav-item">
          <a href="{{route('bank.index')}}"
            class="nav-link {{Request::segment(2)=='bank'?'active':''}}">
            <i class="fas fa-university nav-icon"></i>
            <p>
              Banks
            </p>
          </a>
        </li>
        @endcan
        
        @can('bank-account-view')
        <li class="nav-item">
          <a href="{{route('bankAccount.index')}}"
            class="nav-link {{Request::segment(2)=='bankAccount'?'active':''}}">
            <i class="far fa-circle nav-icon"></i>
            <p>
              Bank Accounts
            </p>
          </a>
        </li>
        @endcan --}}
        
        
        
       
        @php
            $account_categories_segments = ['accountCategory','curAccountCategory','subAccountCategory'];
        @endphp
        @if(Gate::check('accountant-category-view') || Gate::check('cur-accountant-category-view') || Gate::check('sub-accountant-category-view') )
        <li class="nav-item {{ ( in_array(Request::segment(2),$account_categories_segments) )? 'menu-is-opening menu-open' : '' }}">
          <a href="#" class="nav-link {{ ( in_array(Request::segment(2),$account_categories_segments) )? 'active' : '' }}">
			      <i class="fas fa-book nav-icon"></i>
            <p>
              Account Categories
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: {{ ( in_array(Request::segment(2),$account_categories_segments) )? 'block' : 'none' }};">
            @can('accountant-category-view')
            <li class="nav-item">
              <a href="{{route('accountCategory.index')}}"
                class="nav-link {{Request::segment(2)=='accountCategory'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Account Categories
                </p>
              </a>
            </li>
            @endcan
            @can('cur-accountant-category-view')
            <li class="nav-item">
              <a href="{{route('curAccountCategory.index')}}"
                class="nav-link {{Request::segment(2)=='curAccountCategory'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Cur Account Categories
                </p>
              </a>
            </li>
            @endcan
            
            @can('sub-accountant-category-view')
            <li class="nav-item">
              <a href="{{route('subAccountCategory.index')}}"
                class="nav-link {{Request::segment(2)=='subAccountCategory'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Sub Account Categories
                </p>
              </a>
            </li>
            @endcan
          </ul>
        </li>
        @endif
        
        
        @php
            $general_segments = ['users','director','category','paymentType', 'department', 'vendor'];
        @endphp
        @if(Gate::check('user-view') || Gate::check('director-view') || Gate::check('category-view') || Gate::check('payment-type-view') || Gate::check('department-view') || Gate::check('vendor-view') )
        <li class="nav-item {{ ( in_array(Request::segment(2),$general_segments) )? 'menu-is-opening menu-open' : '' }}">
          <a href="#" class="nav-link {{ ( in_array(Request::segment(2),$general_segments) )? 'active' : '' }}">
            <i class="fa fa-cogs nav-icon" aria-hidden="true"></i>
            <p>
              Generals
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: {{ ( in_array(Request::segment(2),$general_segments) )? 'block' : 'none' }};">
            @can('user-view')
            <li class="nav-item">
              <a href="{{route('users.index')}}"
                class="nav-link {{ ( Route::currentRouteName() == 'users.index' || Route::currentRouteName() == 'users.create' || Route::currentRouteName() == 'users.edit')? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Users
                </p>
              </a>
            </li>
            @endcan

            @can('director-view')
            <li class="nav-item">
              <a href="{{route('director.index')}}"
                class="nav-link {{Request::segment(2)=='director'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Directors
                </p>
              </a>
            </li>
            @endcan

            @can('category-view')
            <li class="nav-item">
              <a href="{{route('category.index')}}"
                class="nav-link {{Request::segment(2)=='category'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Categories
                </p>
              </a>
            </li>
            @endcan
    
            @can('payment-type-view')
            <li class="nav-item">
              <a href="{{route('paymentType.index')}}"
                class="nav-link {{Request::segment(2)=='paymentType'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Payment Types
                </p>
              </a>
            </li>
            @endcan
    
            @can('department-view')
            <li class="nav-item">
              <a href="{{route('department.index')}}"
                class="nav-link {{Request::segment(2)=='department'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Departments
                </p>
              </a>
            </li>
            @endcan
    
            @can('vendor-view')
            <li class="nav-item">
              <a href="{{route('vendor.index')}}"
                class="nav-link {{Request::segment(2)=='vendor'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Item Name
                </p>
              </a>
            </li>
            @endcan

            @can('department-bank-view')
            <li class="nav-item">
              <a href="{{route('departmentBank.index')}}"
                class="nav-link {{Request::segment(2)=='departmentBank'?'active':''}}">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Department Banks
                </p>
              </a>
            </li>
            @endcan
          </ul>
        </li>
        @endif
      </ul>
    </nav>
  </div>
</aside>

resources/views/admin/partials/changePassword.blade.php
<div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Change Password</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="alert bg-danger text-light pb-0" id="changePassError" style="display: none">
          </div>
          <form action="" method="post" id="changePassword">
            @csrf
            <div class="form-group">
              <label for="">Old Password</label>
              <input type="password" name="oldpassword" id="oldpassword" class="form-control">
            </div>
            <div class="form-group">
              <label for="">New Password</label>
              <input type="password" name="newpassword" id="newpassword" class="form-control">
            </div>
            <div class="form-group">
              <label for="">Confirm Password</label>
              <input type="password" name="newpassword_confirmation" id="newpassword_confirmation" class="form-control">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" id="btnsubmitPassChange" class="btn btn-primary" form="changePassword">Change Password</button>
        </div>
      </div>
    </div>
  </div>

resources/views/admin/partials/script.blade.php
<!-- jQuery -->
<script src="{{asset('public/backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('public/backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)

</script>
<!-- Bootstrap 4 -->
<script src="{{asset('public/backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
{{-- <!-- ChartJS -->
<script src="{{asset('public/backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('public/backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('public/backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('public/backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script> --}}
<!-- jQuery Knob Chart -->
<script src="{{asset('public/backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('public/backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('public/backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('public/backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('public/backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('public/backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('public/backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('public/backend/dist/js/demo.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{asset('public/backend/dist/js/pages/dashboard.js')}}"></script> --}}

<script src="{{asset('public/backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('public/backend/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('public/backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>

{{-- <script src="{{asset('public/backend/plugins/select2/js/select2.min.js')}}"></script> --}}
<script src="{{asset('public/backend/plugins/select2/js/select2.full.min.js')}}"></script>

<script src="{{asset('public/backend/plugins/sweetalert2/sweetalert2.min.js')}}"></script>

{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.15.5/sweetalert2.min.js"
    integrity="sha512-+uGHdpCaEymD6EqvUR4H/PBuwqm3JTZmRh3gT0Lq52VGDAlywdXPBEiLiZUg6D1ViLonuNSUFdbL2tH9djAP8g=="
    crossorigin="anonymous"></script> --}}

<script src="{{asset('public/backend/plugins/jquery-validation/jquery.validate.js')}}"></script>
<script>

    $(document).ready(function () {
        $(".data-table").DataTable();
        $('.select2').select2();
        $(".alert-dismissible").fadeOut(5000);
    });

    function ErrorMsg(msg,container) {
      $(container).html('<ul style="list-style:none" class="pl-0"></ul>');
      $(container).css('display','block');
      $.each( msg, function( key, value ) {
         $(container).find("ul").append('<li>'+value+'</li>');
      });
    }
    //Show Change Password Modal
    $(document).on('click', '#btnChangePassword', function () {
        $('#newpassword_confirmation').val('');
        $('#newpassword').val('');
        $('#oldpassword').val('');
        $('#changePassError').css('display', 'none');
        $('#changePasswordModal').modal('show');
    });

    //Change Password Ajax Request  
    $('#changePassword').submit(function (e) {
        e.preventDefault();
		// console.log('a',new FormData(this));

		var oldpassword = $('#oldpassword').val();	
		var newpassword = $('#newpassword').val();
		var newpassword_confirmation = $('#newpassword_confirmation').val();
        $.ajax({
            url: "{{route('admin.changePassword')}}",
            type: "POST",
            // data: new FormData(this),
            data: {
				_token: "{{ csrf_token() }}",
				oldpassword: oldpassword,
				newpassword: newpassword,
				newpassword_confirmation: newpassword_confirmation,
			},
			// contentType: false,
            // cache: false,
            // processData: false,
            // dataType: 'JSON',
            beforeSend: function () {
                $('#btnsubmitPassChange').prop('disabled', true);
            },
            success: function (data) {

				console.log('data',data);
                if ($.isEmptyObject(data.error)) {
                    if (data.status) {
                        $('#changePasswordModal').modal('hide');
                        toastr.options = {
                            "closeButton": true
                        }
                        toastr["success"]("Password Changed Successfully")
                    }
                } else {
                    changePasswordErrorMsg(data.error, "#changePassError");
                }
            },
            error: function (jhxr, status, err) {
                console.log(jhxr);
            },
            complete: function () {
                $('#btnsubmitPassChange').prop('disabled', false);
            }
        });
    })

</script>


@stack('custom-script')

resources/views/admin/partials/style.blade.php
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
  <!-- JQVMap -->
  {{-- <link rel="stylesheet" href="{{asset('public/backend/plugins/jqvmap/jqvmap.min.css')}}"> --}}
  <link rel="stylesheet" href="{{asset('public/backend/plugins/select2/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('public/backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">

  <link rel="stylesheet" href="{{asset('public/backend/plugins/sweetalert2/sweetalert2.min.css')}}">
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('public/backend/dist/css/adminlte.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/daterangepicker/daterangepicker.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('public/backend/plugins/summernote/summernote-bs4.min.css')}}">


  <link rel="stylesheet" href="{{asset('public/backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('public/backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('public/backend/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">

  

  {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.15.5/sweetalert2.min.css"
integrity="sha512-gX6K9e/4ewXjtn8Q/oePzgIxs2KPrksR4S2NNMYLxenvF7n7eNon9XbqQxb+5jcqYBVCcncIxqF6fXJYgQtoAg=="
crossorigin="anonymous" /> --}}

  @stack('custom-css')